Fixed some pyflakes warnings (types and copy paste fails)
Originally was:
$ pyflakes __init__.py
  __init__.py:2318: local variable 'event' is assigned to but never used
  __init__.py:4322: redefinition of unused 'unknown_type' from line 4318
  __init__.py:7414: undefined name 'BNFreeTypeParserResult'
  __init__.py:7455: undefined name 'BNFreeTypeParserResult'
  __init__.py:8877: local variable 'param_data' is assigned to but never
  used
  __init__.py:8891: local variable 'param_data' is assigned to but never
  used
  __init__.py:10765: undefined name 'title'
  __init__.py:10768: undefined name 'title'
  __init__.py:11052: undefined name 'mangledName'

Current:
  __init__.py:2318: local variable 'event' is assigned to but never used
  __init__.py:7410: undefined name 'BNFreeTypeParserResult'
  __init__.py:7451: undefined name 'BNFreeTypeParserResult'