cmake: binaryninjaui depends on binaryninjaapi
Fixes building the uinotification example that only links against
`binaryninjaui`.

Without this fix, there's a compilation error about not finding
`binaryninjaapi.h`:

```
In file included from binaryninja-api/examples/uinotification/uinotification.cpp:2:
In file included from binaryninja-api/examples/uinotification/uinotification.h:3:
binaryninja-api/ui/uicontext.h:8:10: fatal error: 'binaryninjaapi.h' file not found
    8 | #include "binaryninjaapi.h"
      |          ^~~~~~~~~~~~~~~~~~
1 error generated.
```