[arm64]: fix broken compilation on windows
no Elvis operator ?:(
api\arch\arm64\il.cpp(894): error C2059: syntax error: ':'

api\arch\arm64\il.cpp(1839): error C7555: use of designated initializers requires at least '/std:c++20'